// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdlpevhfiqlwijynbkvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbHBldmhmaXFsd2lqeW5ia3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzQ4MjEsImV4cCI6MjA2Mjc1MDgyMX0.4pT4eZ-DMQu5j5WhsSxZrQcwwOduq2VXCD3NQ3zQXkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);